CREATE DATABASE appcajeros;

USE appcajeros;

CREATE TABLE cajeros (
    idCajero INT PRIMARY KEY AUTO_INCREMENT,
    numId VARCHAR20 UNIQUE NOT NULL,
    nombre VARCHAR50 NOT NULL,
    apellido VARCHAR50 NOT NULL,
    correo VARCHAR100 UNIQUE NOT NULL,
    passCajero VARCHAR120 NOT NULL
);

CREATE TABLE ventas (
    idVenta INT PRIMARY KEY AUTO_INCREMENT,
    idCajero INT NOT NULL,
    nomCliente VARCHAR(50) NOT NULL,
    valor DOUBLE NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE ventas ADD FOREIGN KEY (idCajero) REFERENCES cajeros(idCajero);